# Permalinks
permalink: pretty

title: Docs Assembler template guide

# For Docs Assembler
markdown_ext: markdown,tsfrg,tsgde,md
source: docs

# For Degging locally
destination: root/_site
sass:
  sass_dir: docs/assets/scss
  style: compressed
defaults:
  -
    scope:
      path: "docs"
      type: pages
    values:
      layout: simple

# Disable all caching
disable_disk_cache: true

# Or more specific cache controls
full_rebuild: true

