# Permalinks
permalink: pretty

title: Docs Assembler demo guides

# For Docs Assembler
markdown_ext: markdown,tsfrg,tsgde,md


# For Docs Assembler
defaults:
  - scope:
      path: "" # Empty string for all files
    values:
      layout: "simple"
      
# Disable all caching
disable_disk_cache: true

# Or more specific cache controls
full_rebuild: true

